apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service1
  namespace: app1
spec:
  destination:
    namespace: app1
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/mapspiral/example-argocd-app1.git
    path: src/service1
    targetRevision: main
  project: project1